### ISSUE TITLE
Simplify the project structure

### ISSUE THREAD

**Issue by ppizarror** [StoccoDavide/acme#1]
Hello, first, thanks for this library!

I had some troubles while attempting to use ``acme``, mainly due to the importation of ``Utils`` (many requirements, like ZLIB). Thus, I copied some files (acme), the ``Eigen`` folder from utils, and created an ``include/acme`` and voilá. Works like magic.

So, I think this library should be simplified, avoiding ``Utils``, and including only the necessary files. Rake, and others, are not necessary, unless if building Matlab API (else, I don't know why you import such a massive submodule). In such a case, there should be an option for CMAKELIST to use only ``acme``+``Eigen``.

Greetings!

**Comment by StoccoDavide** [comment]
Dear ``ppizarror``,

I am very happy that the library can be useful to you and my work is appreciated by other programmers like you.

Coming to the point, I understand your request and appreciate your suggestions. The current structure of the library has been chosen *ad hoc* for our needs. The ``Utils`` Library is a very large sub-module, but it allows us to have many utilities prepared, tested and ready to use. In particular, it implements a much more powerful n-dimensional AABBtree than the one implemented by ``acme``. Have a look at it in case you might need it!

In future versions (which won't be released any time soon due to the current workload) I will certainly try to accommodate your requests by including in ``CMakeList`` the possibility of excluding ``Utils`` and using only ``acme`` and ``Eigen``.

Greetings,
Davide

**Comment by StoccoDavide** [comment]
Is there a public repository from which I can see how you have restructured the `acme` project? Then I can start working on a version that is also suitable for your needs.

Davide

**Comment by ppizarror** [comment]
Hi, I "copied" the private version to a new branch within my fork, see https://github.com/ppizarror/acme/tree/new-structure. The only difference relies on the tests and the CMakeList.

**Comment by StoccoDavide** [comment]
Hi! I removed Utils dependency so I'm closing the issue.

Davide
